before:
  hooks:
    - go mod download
builds:
  - main: ./plugin.go
    goos:
      - windows
      - darwin
      - linux
    env:
      - CGO_ENABLED=0
archives:
  -
    format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
release:
  draft: true
changelog:
  skip: true
